cloud:
  aws:
    credentials:
      accessKey: AKIAWGZDLNNNDMUSQ3P5
      secretKey: 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
    s3:
      bucket: yjk-test-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  profiles:
    active: oauth
    include: oauth
  redis:
    host: localhost
    port: 6379
jwt:
  secret: ${JWT_SECRET}
server:
  port: 8081
